version: '3.8'

services:
  web:
    build: .
    command: gunicorn root.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/project/
      - static_volume:/home/project/static/
      - media_volume:/home/project/media/
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db
    environment:
      - DB_HOST=db
  db:
    image: postgres:13.0-alpine
    container_name: test_deploy_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=bot_commerce_admin
      - POSTGRES_PASSWORD=1
      - POSTGRES_DB=bot_commerce
  nginx:
    build: ./apps/nginx/
    volumes:
      - static_volume:/home/project/static/
      - media_volume:/home/project/media/
    ports:
      - 80:80
    depends_on:
      - web
volumes:
  postgres_data:
  static_volume:
  media_volume:
