version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/project
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
    environment:
      - DB_HOST=db
  db:
    image: postgres:13.0-alpine
    container_name: test_deploy_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=bot_commerce_admin
      - POSTGRES_PASSWORD=1
      - POSTGRES_DB=bot_commerce
volumes:
  postgres_data: